### ISSUE TITLE
Binder fails at postBuild step

### ISSUE THREAD

**Issue by jonesmg** [AMIGA-IAA/hcg_global_hi_analysis#2]
I've noticed that binder seems to always fail at the postBuild step after it has built the conda environment, and downloaded and extracted all of the data. I'm not really sure what's going wrong here.
[hcg_hi_analysis_binder_build.log](https://github.com/AMIGA-IAA/hcg_global_hi_analysis/files/9996252/hcg_hi_analysis_binder_build.log)

**Comment by sebastian-luna-valero** [comment]
Hi,

Let's continue the discussion in https://github.com/AMIGA-IAA/hcg_global_hi_analysis/pull/3

Thanks.
